# Supported funding model platforms
# Uncomment and fill in applicable platforms

# github: # [user1, user2]
# patreon: # single username
# open_collective: # single username
# ko_fi: # single username
# tidelift: # platform-name/package-name
# community_bridge: # project-name
# liberapay: # single username
# issuehunt: # single username
# lfx_crowdfunding: # project-name
# polar: # single username
# custom: # ['url1', 'url2']
