# Composite Action: Setup Node.js with pnpm
# Provides consistent Node.js environment setup across all workflows
#
# Usage:
#   - uses: ./actions/setup-node-pnpm
#     with:
#       node-version: '22'

name: 'Setup Node.js with pnpm'
description: 'Install Node.js and pnpm package manager with caching'
author: 'zircote'

branding:
  icon: 'package'
  color: 'green'

inputs:
  node-version:
    description: 'Node.js version to install'
    required: false
    default: '22'
  install-dependencies:
    description: 'Install dependencies after setup'
    required: false
    default: 'true'
  frozen-lockfile:
    description: 'Use frozen lockfile for install'
    required: false
    default: 'true'
  working-directory:
    description: 'Working directory for commands'
    required: false
    default: '.'

outputs:
  node-version:
    description: 'Installed Node.js version'
    value: ${{ steps.node.outputs.node-version }}
  pnpm-version:
    description: 'Installed pnpm version'
    value: ${{ steps.pnpm-version.outputs.version }}
  cache-hit:
    description: 'Whether the cache was hit'
    value: ${{ steps.node.outputs.cache-hit }}

runs:
  using: 'composite'
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0

    - name: Setup Node.js
      id: node
      uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'
        cache-dependency-path: ${{ inputs.working-directory }}/pnpm-lock.yaml

    - name: Get pnpm version
      id: pnpm-version
      shell: bash
      run: |
        PNPM_VERSION=$(pnpm --version)
        echo "version=$PNPM_VERSION" >> "$GITHUB_OUTPUT"
        echo "Using pnpm $PNPM_VERSION"

    - name: Install dependencies
      if: inputs.install-dependencies == 'true'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        FROZEN: ${{ inputs.frozen-lockfile }}
      run: |
        if [[ "$FROZEN" == "true" ]]; then
          pnpm install --frozen-lockfile
        else
          pnpm install
        fi
